from models.Base import Base
from models.Appointment import Appointment
from models.Department import Department
from models.DoctorModel import Doctor
from models.Medication import Medication
from models.Patient import Patient
from models.Payment import Payment
from models.Prescribes import Prescribes
from models.Room import Room
